In [1]:
import random
while True:
    user_action = input("Enter a choice (Stone, Paper, Scissors):")
    possible_actions = ["Stone", "Paper", "Scissors"]
    computer_action = random.choice(possible_actions)
    print(f"\nYou Choose {user_action}, Computer Choose {computer_action}.\n")
    if user_action == computer_action:
        print(f"Both players selected {user_action}. It's a tie!")
    elif user_action == "Stone":
        if computer_action == "Scissors":
            print("Stone smashes Scissors! You win!")
        else:
            print("Paper covers Stone! You lose.")
    elif user_action == "Paper":
        if computer_action == "Stone":
            print("Paper covers Stone! You win!")
        else:
            print("Scissors cuts Paper! You lose.")
    elif user_action == "Scissors":
        if computer_action == "Paper":
            print("Scissors cuts Paper! You win!")
        else:
            print("Stone smashes scissors! You lose.")
    play_again = input("Play again? (y/n): ")
    if play_again.lower() != "y":
        break


You Choose Stone, Computer Choose Stone.

Both players selected Stone. It's a tie!

You Choose Paper, Computer Choose Scissors.

Scissors cuts Paper! You lose.

You Choose Stone, Computer Choose Stone.

Both players selected Stone. It's a tie!


In [2]:
import numpy as np
import random
from time import sleep
def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))
def possibilities(board):
	l = []
	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)
def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)
def row_win(board, player):
	for x in range(len(board)):
		win = True
		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue
		if win == True:
			return(win)
	return(win)
def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue
		if win == True:
			return(win)
	return(win)
def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win
def evaluate(board):
	winner = 0
	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):
			winner = player
	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner
def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[1 0 0]
 [0 0 0]
 [0 0 2]]
Board after 3 move
[[1 1 0]
 [0 0 0]
 [0 0 2]]
Board after 4 move
[[1 1 0]
 [0 2 0]
 [0 0 2]]
Board after 5 move
[[1 1 0]
 [1 2 0]
 [0 0 2]]
Board after 6 move
[[1 1 0]
 [1 2 2]
 [0 0 2]]
Board after 7 move
[[1 1 1]
 [1 2 2]
 [0 0 2]]
Winner is: 1


In [3]:
import os
import time

board = [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
player = 1

# Win Flags
Win = 1
Draw = -1
Running = 0
Stop = 1

Game = Running
Mark = 'X'


def DrawBoard():
    print(" %c | %c | %c " % (board[1], board[2], board[3]))
    print("___|___|___")
    print(" %c | %c | %c " % (board[4], board[5], board[6]))
    print("___|___|___")
    print(" %c | %c | %c " % (board[7], board[8], board[9]))
    print(" | | ")


def CheckPosition(x):
    if board[x] == ' ':
        return True
    else:
        return False


def CheckWin():
    global Game

    if board[1] == board[2] and board[2] == board[3] and board[1] != ' ':
        Game = Win
    elif board[4] == board[5] and board[5] == board[6] and board[4] != ' ':
        Game = Win
    elif board[7] == board[8] and board[8] == board[9] and board[7] != ' ':
        Game = Win
    elif board[1] == board[4] and board[4] == board[7] and board[1] != ' ':
        Game = Win
    elif board[2] == board[5] and board[5] == board[8] and board[2] != ' ':
        Game = Win
    elif board[3] == board[6] and board[6] == board[9] and board[3] != ' ':
        Game = Win
    elif board[1] == board[5] and board[5] == board[9] and board[5] != ' ':
        Game = Win
    elif board[3] == board[5] and board[5] == board[7] and board[5] != ' ':
        Game = Win
    elif board[1] != ' ' and board[2] != ' ' and board[3] != ' ' and \
            board[4] != ' ' and board[5] != ' ' and board[6] != ' ' and \
            board[7] != ' ' and board[8] != ' ' and board[9] != ' ':
        Game = Draw
    else:
        Game = Running


print("Tic-Tac-Toe Game Designed By Sourabh Somani")
print("Player 1 [X] --- Player 2 [O]\n")
print()
print()
print("Please Wait...")
time.sleep(3)

while Game == Running:
    os.system('cls')
    DrawBoard()

    if player % 2 != 0:
        print("Player 1's chance")
        Mark = 'X'
    else:
        print("Player 2's chance")
        Mark = 'O'

    choice = int(input("Enter the position between [1-9] where you want to mark: "))
    if CheckPosition(choice):
        board[choice] = Mark
        player += 1
        CheckWin()

    os.system('cls')
    DrawBoard()

    if Game == Draw:
        print("Game Draw")
    elif Game == Win:
        player -= 1
        if player % 2 != 0:
            print("Player 1 Won")
        else:
            print("Player 2 Won")

Tic-Tac-Toe Game Designed By Sourabh Somani
Player 1 [X] --- Player 2 [O]



Please Wait...
   |   |   
___|___|___
   |   |   
___|___|___
   |   |   
 | | 
Player 1's chance
   |   | X 
___|___|___
   |   |   
___|___|___
   |   |   
 | | 
   |   | X 
___|___|___
   |   |   
___|___|___
   |   |   
 | | 
Player 2's chance
   | O | X 
___|___|___
   |   |   
___|___|___
   |   |   
 | | 
   | O | X 
___|___|___
   |   |   
___|___|___
   |   |   
 | | 
Player 1's chance
   | O | X 
___|___|___
   |   |   
___|___|___
   |   | X 
 | | 
   | O | X 
___|___|___
   |   |   
___|___|___
   |   | X 
 | | 
Player 2's chance
 O | O | X 
___|___|___
   |   |   
___|___|___
   |   | X 
 | | 
 O | O | X 
___|___|___
   |   |   
___|___|___
   |   | X 
 | | 
Player 1's chance
 O | O | X 
___|___|___
   |   | X 
___|___|___
   |   | X 
 | | 
Player 1 Won


In [5]:
import random
from datetime import datetime
def print_board(board):
    print("\n    1   2   3 \n")
    print("1   " + board[0][0] + " | " + board[0][1] + " | " + board[0][2])
    print("   ---+---+---")
    print("2   " + board[1][0] + " | " + board[1][1] + " | " + board[1][2])
    print("   ---+---+---")
    print("3   " + board[2][0] + " | " + board[2][1] + " | " + board[2][2] + "\n")
def check_row(board, row):
    return (board[row][0] == board[row][1] and board[row][1] == board[row][2] and board[row][0] != " ")
def check_column(board, col):
    return (board[0][col] == board[1][col] and board[1][col] == board[2][col] and board[0][col] != " ")
def check_diagonals(board):
    return (board[0][0] == board[1][1] and board[1][1] == board[2][2] and board[0][0] != " ") or\
            (board[2][0] == board[1][1] and board[1][1] == board[0][2] and board[2][0] != " ")
def check_winner(board):
    for i in range(3):
        if check_row(board, i):
            return True
        if check_column(board, i):
            return True
    if check_diagonals(board):
        return True
    return False
def is_board_full(board):
    for item in board:
        if " " in item:
            return False
    return True
def play(board):
    while True:
        row = input("Enter row number: ")
        while not row.isdigit() or int(row) < 1 or int(row) > 3:
            row = input("Enter row number between 1-3: ")
        row = int(row)
        col = input("Enter column number: ")
        while not col.isdigit() or int(col) < 1 or int(col) > 3:
            col = input("Enter column number between 1-3: ")
        col = int(col)
        if board[row-1][col-1] != " ":
            print("Pick an empty box!")
        else:
            return (row-1, col-1)
def play_random(board):
    possible_moves = []
    for row in range(len(board)):
        for col in range(len(board[0])):
            if board[row][col] == " ":
                possible_moves.append((row, col))
    
    return possible_moves[random.randrange(len(possible_moves))]
def main():
    random.seed(datetime.now())
    print("\n== Tic Tac Toe ==")
    # Create an empty board
    board = [ 
        [" ", " ", " "],
        [" ", " ", " "],
        [" ", " ", " "]
    ]
    # Create 2 players
    players = ["X", "O"]
    # Player X plays first
    turn = 0
    while not is_board_full(board):
        print_board(board)
        if turn == 0:
            # User input
            print("You play!")
            row, col = play(board)
            board[row][col] = players[turn]
            
        else:
            # Compuuter plays
            print("Computer plays!")
            row, col = play_random(board)
            board[row][col] = players[turn]
        # Check if the player won
        if check_winner(board):
            print_board(board)
            print("You won!" if turn == 0 else "Computer won!")
            break
        
        # Select the next player
        turn = 1 - turn
    
    else:
        print_board(board)
        print("It's a tie!")
main()

C:\Users\Aryan Kumar\AppData\Local\Temp\ipykernel_22828\3955610893.py:54: DeprecationWarning: Seeding based on hashing is deprecated
since Python 3.9 and will be removed in a subsequent version. The only 
supported seed types are: None, int, float, str, bytes, and bytearray.
  random.seed(datetime.now())



== Tic Tac Toe ==

    1   2   3 

1     |   |  
   ---+---+---
2     |   |  
   ---+---+---
3     |   |  

You play!

    1   2   3 

1     |   |  
   ---+---+---
2     |   |  
   ---+---+---
3     |   | X

Computer plays!

    1   2   3 

1     |   |  
   ---+---+---
2     |   | O
   ---+---+---
3     |   | X

You play!

    1   2   3 

1     |   |  
   ---+---+---
2     | X | O
   ---+---+---
3     |   | X

Computer plays!

    1   2   3 

1   O |   |  
   ---+---+---
2     | X | O
   ---+---+---
3     |   | X

You play!

    1   2   3 

1   O |   | X
   ---+---+---
2     | X | O
   ---+---+---
3     |   | X

Computer plays!

    1   2   3 

1   O |   | X
   ---+---+---
2   O | X | O
   ---+---+---
3     |   | X

You play!
Pick an empty box!
Pick an empty box!

    1   2   3 

1   O |   | X
   ---+---+---
2   O | X | O
   ---+---+---
3   X |   | X

You won!


In [ ]:
import random
name = input("What is your name? ")
print("Good Luck ! ", name)
words = ['rainbow', 'computer', 'science', 'programming',
		'python', 'mathematics', 'player', 'condition',
		'reverse', 'water', 'board', 'geeks']
word = random.choice(words)
print("Guess the characters")
guesses = ''
turns = 12
while turns > 0:
    failed = 0
for char in word:
		if char in guesses:
			print(char, end=" ")
		else:
			print("_")
			failed += 1
		if (failed == 0):
			print("You Win")
			print("The word is: ", word)
			break
			print()
			guess = input("guess a character:")
			guesses += guess
		if guess not in word:
			turns -= 1
			print("Wrong")
			print("You have", + turns, 'more guesses')
		if turns == 0:
			print("You Loose")


In [ ]:
import numpy as np
import random
from time import sleep
def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))
def possibilities(board):
	l = []
	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)
def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)
def row_win(board, player):
	for x in range(len(board)):
		win = True
		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue
		if win == True:
			return(win)
	return(win)
def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue
		if win == True:
			return(win)
	return(win)
def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win
def evaluate(board):
	winner = 0
	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):
			winner = player
	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner
def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[1 0 0]
 [0 0 0]
 [0 0 2]]
Board after 3 move
[[1 1 0]
 [0 0 0]
 [0 0 2]]
Board after 4 move
[[1 1 0]
 [0 2 0]
 [0 0 2]]
Board after 5 move
[[1 1 0]
 [1 2 0]
 [0 0 2]]
Board after 6 move
[[1 1 0]
 [1 2 2]
 [0 0 2]]
Board after 7 move
[[1 1 1]
 [1 2 2]
 [0 0 2]]
Winner is: 1


In [ ]:
# import required modules
import turtle
import time
import random

delay = 0.1
score = 0
high_score = 0


# Creating a window screen
wn = turtle.Screen()
wn.title("Snake Game")
wn.bgcolor("blue")
# the width and height can be put as user's choice
wn.setup(width=600, height=600)
wn.tracer(0)

# head of the snake
head = turtle.Turtle()
head.shape("square")
head.color("white")
head.penup()
head.goto(0, 0)
head.direction = "Stop"

# food in the game
food = turtle.Turtle()
colors = random.choice(['red', 'green', 'black'])
shapes = random.choice(['square', 'triangle', 'circle'])
food.speed(0)
food.shape(shapes)
food.color(colors)
food.penup()
food.goto(0, 100)

pen = turtle.Turtle()
pen.speed(0)
pen.shape("square")
pen.color("white")
pen.penup()
pen.hideturtle()
pen.goto(0, 250)
pen.write("Score : 0 High Score : 0", align="center",
		font=("candara", 24, "bold"))


# assigning key directions
def group():
	if head.direction != "down":
		head.direction = "up"


def godown():
	if head.direction != "up":
		head.direction = "down"


def goleft():
	if head.direction != "right":
		head.direction = "left"


def goright():
	if head.direction != "left":
		head.direction = "right"


def move():
	if head.direction == "up":
		y = head.ycor()
		head.sety(y+20)
	if head.direction == "down":
		y = head.ycor()
		head.sety(y-20)
	if head.direction == "left":
		x = head.xcor()
		head.setx(x-20)
	if head.direction == "right":
		x = head.xcor()
		head.setx(x+20)


wn.listen()
wn.onkeypress(group, "w")
wn.onkeypress(godown, "s")
wn.onkeypress(goleft, "a")
wn.onkeypress(goright, "d")

segments = []


# Main Gameplay
while True:
	wn.update()
	if head.xcor() > 290 or head.xcor() < -290 or head.ycor() > 290 or head.ycor() < -290:
		time.sleep(1)
		head.goto(0, 0)
		head.direction = "Stop"
		colors = random.choice(['red', 'blue', 'green'])
		shapes = random.choice(['square', 'circle'])
		for segment in segments:
			segment.goto(1000, 1000)
		segments.clear()
		score = 0
		delay = 0.1
		pen.clear()
		pen.write("Score : {} High Score : {} ".format(
			score, high_score), align="center", font=("candara", 24, "bold"))
	if head.distance(food) < 20:
		x = random.randint(-270, 270)
		y = random.randint(-270, 270)
		food.goto(x, y)

		# Adding segment
		new_segment = turtle.Turtle()
		new_segment.speed(0)
		new_segment.shape("square")
		new_segment.color("orange") # tail colour
		new_segment.penup()
		segments.append(new_segment)
		delay -= 0.001
		score += 10
		if score > high_score:
			high_score = score
		pen.clear()
		pen.write("Score : {} High Score : {} ".format(
			score, high_score), align="center", font=("candara", 24, "bold"))
	# Checking for head collisions with body segments
	for index in range(len(segments)-1, 0, -1):
		x = segments[index-1].xcor()
		y = segments[index-1].ycor()
		segments[index].goto(x, y)
	if len(segments) > 0:
		x = head.xcor()
		y = head.ycor()
		segments[0].goto(x, y)
	move()
	for segment in segments:
		if segment.distance(head) < 20:
			time.sleep(1)
			head.goto(0, 0)
			head.direction = "stop"
			colors = random.choice(['red', 'blue', 'green'])
			shapes = random.choice(['square', 'circle'])
			for segment in segments:
				segment.goto(1000, 1000)
			segments.clear()

			score = 0
			delay = 0.1
			pen.clear()
			pen.write("Score : {} High Score : {} ".format(
				score, high_score), align="center", font=("candara", 24, "bold"))
	time.sleep(delay)

wn.mainloop()
